### PR TITLE
Room Details & User Case Addition

### PR DESCRIPTION
**Pull request by DaffaBarin**
Addition
- added nullable 'image' column for user
- room_details table in database (relation done)
- business logic done in ApiRoomDetailsController (CRUD)
- user controller getAllUsers & updateUser
- Branch feat/room_details had been tested
- Server live at https://hotelist-be.herokuapp.com/
- Database live at heroku postgreql

Please review or test from the documention here https://documenter.getpostman.com/view/14606023/UVypzxTz

### CODE REVIEW

**Review by whauzan — APPROVED** [review]
All endpoint has been tested and works properly. Nice work!

**Review by summerghost — APPROVED** [review]

**Review by Bagja9102Kurniawan — APPROVED** [review]
LGTM!

**Review by Bagja9102Kurniawan — APPROVED** [review]
LGTM!

**Review by vincentiusar — APPROVED** [review]
LGTM

**Pull request merged**
